name: Build and Push Docker Images

on:
  push:
    branches:
      - deploy/ecs-alb


permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 830278489152.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::830278489152:role/githubactions-chatapp
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push frontend
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_USER_SERVICE="${{ secrets.NEXT_PUBLIC_USER_SERVICE }}" \
          --build-arg NEXT_PUBLIC_CHAT_SERVICE="${{ secrets.NEXT_PUBLIC_CHAT_SERVICE }}" \
          --build-arg FRONtEND_URL="${{ secrets.FRONTEND_URL }}" \
            -t $ECR_REGISTRY/chatapp/frontend:${GITHUB_SHA} \
            -t $ECR_REGISTRY/chatapp/frontend:latest \
            ./frontend

          docker push $ECR_REGISTRY/chatapp/frontend:${GITHUB_SHA}
          docker push $ECR_REGISTRY/chatapp/frontend:latest

      - name: Build and push user service
        run: |
          docker build \
            -t $ECR_REGISTRY/chatapp/user:${GITHUB_SHA} \
            -t $ECR_REGISTRY/chatapp/user:latest \
            ./backend/user

          docker push $ECR_REGISTRY/chatapp/user:${GITHUB_SHA}
          docker push $ECR_REGISTRY/chatapp/user:latest

      - name: Build and push chat service
        run: |
          docker build \
            -t $ECR_REGISTRY/chatapp/chat:${GITHUB_SHA} \
            -t $ECR_REGISTRY/chatapp/chat:latest \
            ./backend/chat

          docker push $ECR_REGISTRY/chatapp/chat:${GITHUB_SHA}
          docker push $ECR_REGISTRY/chatapp/chat:latest

      - name: Build and push mail service
        run: |
          docker build \
            -t $ECR_REGISTRY/chatapp/mail:${GITHUB_SHA} \
            -t $ECR_REGISTRY/chatapp/mail:latest \
            ./backend/mail

          docker push $ECR_REGISTRY/chatapp/mail:${GITHUB_SHA}
          docker push $ECR_REGISTRY/chatapp/mail:latest
